---
- hosts: all
  become: yes
  remote_user: ubuntu

  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_prompt:
    - name: arangodb_root_password
      prompt: "Password for ArangoDB root account"

    - name: ssl_cert_path
      prompt: "Path to parent SSL cert directory"
      default: "/etc/letsencrypt/live/multinet.app/"

  tasks:
    # https://www.arangodb.com/download-major/ubuntu/
    - name: Add arangodb release key
      apt_key:
        url: https://download.arangodb.com/arangodb35/DEBIAN/Release.key
        state: present
      become: true

    - name: Create arangodb list file
      shell: echo 'deb https://download.arangodb.com/arangodb35/DEBIAN/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
      become: true

    - name: Install arangodb dependency
      apt:
        name: apt-transport-https
        update_cache: true
      become: true

    - name: Install arangodb
      apt:
        name: arangodb3=3.5.2-1
      become: true

    - name: Stop arangodb service
      systemd:
        name: arangodb3
        state: stopped
      become: true

    - name: Overwrite the default arangodb password
      shell: ARANGODB_DEFAULT_ROOT_PASSWORD={{ arangodb_root_password }} arango-secure-installation
      become: true

    - name: Copy the compressed SSL certificate files to the server
      copy:
        src: '{{ ssl_cert_path }}'
        dest: /home/ubuntu/
        follow: yes
        mode: u=rw,g=,o=

    - name: Combine the chain and the private key into one file (required by arango)
      shell:
        chdir: /home/ubuntu/
        cmd: cat fullchain.pem privkey.pem > server.pem

    - name: Set the combined file as 600 permission
      file:
        path: /home/ubuntu/server.pem
        mode: u=rw,g=,o=

    - name: Add an exception to the permissions for the arangodb user
      shell:
        chdir: /home/ubuntu/
        cmd: setfacl -m u:arangodb:r /home/ubuntu/server.pem

    - name: Add the SSL filepath to the config
      lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^\[ssl\]'
        line: "\n[ssl]\nkeyfile = /home/ubuntu/server.pem"

    - name: Enable arangodb to listen on all interfaces
      lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^endpoint ='
        line: "endpoint = ssl://0.0.0.0:8529"
      become: true

    - name: Start arangodb service
      systemd:
        name: arangodb3
        state: restarted
      become: true
