name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and test on Ubuntu - Node 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      # Copy Env File
      - run: cp .env.default .env

      # Build and test Multinet server.
      - run: pip install pipenv

      - uses: actions/cache@v1
        id: multinet-cache
        with:
          path: /home/runner/.local/share/virtualenvs/
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/work/multinet-server/multinet-server/Pipfile.lock') }}-pipenv-cache-2

      - name: Install pipenv packages
        if: steps.multinet-cache.outputs.cache-hit != 'true'
        run: pipenv install --dev --deploy

      - run: pipenv run lint
      - run: pipenv run format
      - run: pipenv run typecheck
      - run: pipenv run test
