name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and test on Ubuntu - Node 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      # Copy Env File
      - run: cp .env.default .env

      # Build and test Multinet server.
      - run: pip install pipenv
      - run: pipenv install --dev --deploy
      - run: pipenv run lint
      - run: pipenv run format
      - run: pipenv run typecheck
      - run: pipenv run test

      # Build and test Multinet client app.
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: actions/cache@v1
        id: client-cache
        with:
          path: /home/runner/work/multinet/multinet/client/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('/home/runner/work/multinet/multinet/client/yarn.lock') }}-client-cache

      - name: Install yarn packages
        if: steps.client-cache.outputs.cache-hit != 'true'
        run: cd client && yarn install

      - run: cd client && yarn lint
      - run: cd client && yarn lint:test
      - run: pipenv run test-server-up
      - run: cd client && yarn test:client:up
      - run: cd client && yarn test
      - run: cd client && yarn build

      # Build and test Multinet client library.
      - uses: actions/cache@v1
        id: multinetjs-cache
        with:
          path: /home/runner/work/multinet/multinet/multinetjs/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('/home/runner/work/multinet/multinet/multinetjs/yarn.lock') }}-multinetjs-cache

      - name: Install yarn packages
        if: steps.multinetjs-cache.outputs.cache-hit != 'true'
        run: cd multinetjs && yarn install

      - run: cd multinetjs && yarn build
      - run: cd multinetjs && yarn lint
      - run: cd multinetjs && yarn test
